apiVersion: backupper.cattle.io/v1
kind: BackupEncryptionConfig
metadata:
  name: testconfig
  namespace: default
resources:
  - resources:
    - secrets
    providers:
      - aescbc:
          keys:
          - name: key1
            secret: c2VjcmV0IGlzIHNlY3VyZQ==
---
apiVersion: v1
kind: Namespace
metadata:
  name: backupper
---
apiVersion: backupper.cattle.io/v1
kind: Backup
metadata:
  name: test-tgz-backup
  namespace: default
spec:
  backupFileName: tgz-backup
  backupStorageLocation:
    local: test-backup-location-local
  backupTemplate: mcm-backup-template
  encryptionConfigName: testconfig
  encryptionConfigNamespace: default