apiVersion: backupper.cattle.io/v1
kind: BackupEncryptionConfig
metadata:
  name: testconfig
  namespace: default
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: c2VjcmV0IGlzIHNlY3VyZQ==
---
apiVersion: backupper.cattle.io/v1
kind: Restore
metadata:
  name: restore-s3-demo
  namespace: default
spec:
  backupFileName: backup-demo.tar.gz
  backupStorageLocation:
    s3objectStore:
      credentials: default/creds
      bucketName: rajashree-backup-test
      folder: ecm1
      region: us-west-2
      endpoint: s3.us-west-2.amazonaws.com
  backupTemplate: mcm-backup-template
  encryptionConfigName: testconfig
  encryptionConfigNamespace: default