apiVersion: resources.cattle.io/v1
kind: Restore
metadata:
  name: restore-s3-demo
  namespace: default
spec:
  backupFilename: default-s3-backup-demo-84bf8dd8-0ef3-4240-8ad1-fc7ec308e216-2020-08-24T12#49#25-07#00.tar.gz
  storageLocation:
    s3:
      credentialSecretName: creds
      bucketName: rajashree-backup-test
      folder: ecm1
      region: us-west-2
      endpoint: s3.us-west-2.amazonaws.com
  encryptionConfigName: test-encryptionconfig