apiVersion: backupper.cattle.io/v1
kind: Restore
metadata:
  name: restore-s3-demo
  namespace: default
spec:
  backupFileName: backup1.tar.gz
  backupStorageLocation:
    s3objectStore:
      credentials: default/creds
      bucketName: rajashree-backup-test
      folder: ecm1
      region: us-west-2
      endpoint: s3.us-west-2.amazonaws.com
  backupTemplate: mcm-backup-template
  encryptionConfigName: testconfig
  encryptionConfigNamespace: default