apiVersion: backupper.cattle.io/v1
kind: Backup
metadata:
  name: secret-encrypt-backup
spec:
  backupStorageLocation:
    local: secret-encrypt-backup
  backupTemplate: mcm-backup-template
  backupEncryptionSecretName: mysecret