apiVersion: backupper.cattle.io/v1
kind: BackupEncryptionConfig
metadata:
  name: testconfig
  namespace: default
resources:
  - resources:
    - secrets
    providers:
      - aescbc:
          keys:
          - name: key1
            secret: c2VjcmV0IGlzIHNlY3VyZQ==
---
apiVersion: v1
kind: Namespace
metadata:
  name: backupper
---
apiVersion: backupper.cattle.io/v1
kind: Backup
metadata:
  name: secret-encrypt-backup
  namespace: default
spec:
  backupStorageLocation:
    local: secret-encrypt-backup
  backupTemplate: mcm-backup-template
  backupEncryptionConfigName: testconfig
  backupEncryptionConfigNamespace: default