apiVersion: resources.cattle.io/v1
kind: Restore
metadata:
  name: restore-s3-demo
  namespace: default
spec:
  backupFilename: default-s3-backup-demo-55323ad5-d6a0-4106-b80f-9368c2bb69ad-2020-08-16T22#49#11Z.tar.gz
  storageLocation:
    s3:
      credentialSecretName: creds
      bucketName: rajashree-backup-test
      folder: ecm1
      region: us-west-2
      endpoint: s3.us-west-2.amazonaws.com
  encryptionConfigName: test-encryptionconfig