apiVersion: v1
kind: Secret
metadata:
  name: backup-secret
type: Opaque
data:
  secret: E7206F8710099E6DF3E10EBCFF3D4B1A
---
apiVersion: backupper.cattle.io/v1
kind: Backup
metadata:
  name: secret-encrypt-backup
spec:
  backupStorageLocation:
    local: secret-encrypt-backup
  backupTemplate: mcm-backup-template
  encryptionConfigPath: examples/encryptionConfig.yaml
  backupEncryptionConfig:
    encryptionProvider: aescbc
    encryptionSecret: backup-secret