apiVersion: backupper.cattle.io/v1
kind: Backup
metadata:
  name: secret-encrypt-backup
spec:
  backupStorageLocation:
    local: secret-encrypt-backup
  resources:
    - apiGroup: "v1"
      kinds: "^namespaces$"
      resourceNameRegex: "^cattle-|^p-|^c-|^local$|^user-|^u-"
    - apiGroup: "v1"
      kinds: "^secrets$|^serviceaccounts$"
      namespaceRegex: "^cattle-|^p-|^c-|^local$|^user-|^u-"
    - apiGroup: "rbac.authorization.k8s.io/v1"
      kinds: "^roles$|^rolebindings$"
      namespaceRegex: "^cattle-|^p-|^c-|^local$|^user-|^u-"
    - apiGroup: "rbac.authorization.k8s.io/v1"
      kinds: "^clusterroles$|^clusterrolebindings$"
      resourceNameRegex: "^cattle-|^clusterrolebinding-|^globaladmin-user-|^grb-u-"
    - apiGroup: "management.cattle.io/v3"
      kinds: "."
    - apiGroup: "project.cattle.io/v3"
      kinds: "."
  backupEncryptionSecretName: mysecret