apiVersion: backupper.cattle.io/v1
kind: Backup
metadata:
  name: my-backup-path
spec:
  backupStorageLocation:
    local: rancher-backup-path
  groupVersions: "v1,rbac.authorization.k8s.io/v1,management.cattle.io/v3,project.cattle.io/v3"