apiVersion: resources.cattle.io/v1
kind: Backup
metadata:
  name: test-default-location-recurring-backup
  namespace: default
spec:
  resourceSetName: ecm-resource-set
  encryptionConfigName: test-encryptionconfig
  schedule: "@every 1m"
  retention: "4m"