apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: backups.backupper.cattle.io
spec:
  group: backupper.cattle.io
  names:
    kind: Backup
    plural: backups
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            backupEncryptionConfigName:
              type: string
            backupEncryptionConfigNamespace:
              type: string
            backupFileName:
              type: string
            backupStorageLocation:
              properties:
                local:
                  type: string
                s3objectStore:
                  nullable: true
                  properties:
                    accessKey:
                      type: string
                    bucketName:
                      type: string
                    endpoint:
                      type: string
                    endpointCa:
                      type: string
                    folder:
                      type: string
                    region:
                      type: string
                    secretKey:
                      type: string
                  type: object
              type: object
            backupTemplate:
              type: string
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    type: string
                  lastUpdateTime:
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                type: object
              nullable: true
              type: array
            summary:
              type: string
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
