apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: backupencryptionconfigs.backupper.cattle.io
spec:
  group: backupper.cattle.io
  names:
    kind: BackupEncryptionConfig
    plural: backupencryptionconfigs
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        resources:
          items:
            properties:
              providers:
                items:
                  properties:
                    aescbc:
                      nullable: true
                      properties:
                        keys:
                          items:
                            properties:
                              name:
                                type: string
                              secret:
                                type: string
                            type: object
                          nullable: true
                          type: array
                      type: object
                    aesgcm:
                      nullable: true
                      properties:
                        keys:
                          items:
                            properties:
                              name:
                                type: string
                              secret:
                                type: string
                            type: object
                          nullable: true
                          type: array
                      type: object
                    identity:
                      nullable: true
                      type: object
                    kms:
                      nullable: true
                      properties:
                        cacheSize:
                          nullable: true
                          type: integer
                        endpoint:
                          type: string
                        name:
                          type: string
                        timeout:
                          nullable: true
                          type: string
                      type: object
                    secretbox:
                      nullable: true
                      properties:
                        keys:
                          items:
                            properties:
                              name:
                                type: string
                              secret:
                                type: string
                            type: object
                          nullable: true
                          type: array
                      type: object
                  type: object
                nullable: true
                type: array
              resources:
                items:
                  type: string
                nullable: true
                type: array
            type: object
          nullable: true
          type: array
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
