apiVersion: resources.cattle.io/v1
kind: ResourceSet
metadata:
  name: ecm-resource-set
resourceSelectors:
  - apiGroup: "v1"
    kindsRegex: "^namespaces$"
    resourceNameRegex: "^cattle-|^p-|^c-|^local$|^user-|^u-"
  - apiGroup: "v1"
    kindsRegex: "^secrets$|^serviceaccounts$"
    namespaceRegex: "^cattle-|^p-|^c-|^local$|^user-|^u-"
  - apiGroup: "rbac.authorization.k8s.io/v1"
    kindsRegex: "^roles$|^rolebindings$"
    namespaceRegex: "^cattle-|^p-|^c-|^local$|^user-|^u-"
  - apiGroup: "rbac.authorization.k8s.io/v1"
    kindsRegex: "^clusterrolebindings$"
    resourceNameRegex: "^cattle-|^clusterrolebinding-|^globaladmin-user-|^grb-u-"
  - apiGroup: "rbac.authorization.k8s.io/v1"
    kindsRegex: "^clusterroles$"
    resourceNameRegex: "^cattle-|^p-|^c-|^local-|^user-|^u-|^project-|^create-ns$"
  - apiGroup: "apiextensions.k8s.io/v1beta1"
    kindsRegex: "."
    resourceNameRegex: "management.cattle.io$|project.cattle.io$"
  - apiGroup: "management.cattle.io/v3"
    kindsRegex: "."
  - apiGroup: "project.cattle.io/v3"
    kindsRegex: "."
