apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: faketests.backupper.cattle.io
spec:
  group: backupper.cattle.io
  names:
    kind: FakeTest
    plural: faketests
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            valInt:
              type: integer
            valStr:
              type: string
          type: object
        status:
          properties:
            generation:
              type: integer
            version:
              type: string
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
