apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: resourcesets.backupper.cattle.io
spec:
  group: backupper.cattle.io
  names:
    kind: ResourceSet
    plural: resourcesets
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        resourceSelectors:
          items:
            properties:
              apiGroup:
                type: string
              kinds:
                items:
                  type: string
                nullable: true
                type: array
              kindsRegex:
                type: string
              labelSelectors:
                nullable: true
                properties:
                  matchExpressions:
                    items:
                      properties:
                        key:
                          type: string
                        operator:
                          type: string
                        values:
                          items:
                            type: string
                          nullable: true
                          type: array
                      type: object
                    nullable: true
                    type: array
                  matchLabels:
                    additionalProperties:
                      type: string
                    nullable: true
                    type: object
                type: object
              namespaceRegex:
                type: string
              namespaces:
                items:
                  type: string
                nullable: true
                type: array
              resourceNameRegex:
                type: string
              resourceNames:
                items:
                  type: string
                nullable: true
                type: array
            type: object
          nullable: true
          type: array
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
